### ISSUE TITLE
Option to ignore a dependency

### ISSUE THREAD

**Issue by tjconcept** [clux/npm-graph#8]
I primarily use your module for inspecting the trees of my client apps before bundling with browserify.

I use transforms like https://github.com/jadejs/brjade that inlines stuff and the problem is that this makes npm-graph look for the entire jade module with all its dependencies. It would be nice if I could tell it to ignore e.g. `require('jade')`.

**Comment by clux** [comment]
Yeah, I agree a hide flag could be useful. There's already functions in there for filtering, could probably extend those with some options from the cli entry point. Not on the top of my things to look at right now, but feel free to submit a PR :)

**Comment by clux** [comment]
Implemented in npm-graph@0.5.0.

There is an issue that I have yet to look into #9, which is that the leaf node (jade) sometimes does not show up. But at least it hides the output.

**Comment by tjconcept** [comment]
:+1:
